= Multivector Tutorial and Reference
:sectnums:
:toc:
:toc-placement!:

== Introduction

A multivector is a a generic container that behaves just like a `std::vector`
except its iterators also behave just like `std::vector`.
And since `std::vector` is used in the underlying representation, we can make
hierarchies that benefit from both cache friendly locality of reference and
C++11 move semantics.

A multivector is ideally suited to represent trees that we often encounter in
software:
document object models, window hierarchies, telecom messages, configurators, 
filesystems, online shopping carts, multiple choice tests, user lists, etc. 

toc::[]

=== Example

A simple multivector of integers can be conveniently created with an initializer
list:

[source,c++]
----
#include <wythe/multivector.h>
auto m = wythe::multivector<int>{1, 2, {10, 11, 12, {100}}, 3};
----

and displayed using the `to_text` convenience function:

[source,c++]
----
std::cout << wythe::to_text(m);
----

resulting in:

----
    1
    2
      10
      11
      12
        100
    3
----

There are 3 vectors in the above multivector:
1, 2, and 3; 10, 11, and 12; and 100.

12 is the parent of 100, 2 is the parent of 10, and the parent of 1 is
considered the *root*.

`iterators` for multivectors are called `cursors` and are the means of navigation.
They are random access within the same vector.
Unlike regular iterators they have the vector functions you would expect:
`begin()`, `end()`, `emplace()`, etc.

For cursors, `begin()`  and `end()` behave like `std::vector` iterators.
In multivectors, however, there can be many different `begin()` and `end()` cursors.
The above example has 3 each.
All cursors that are part of the same multivector are comparable.
So the `end()` of the `{10, 11, 12}` vector is comparable (and not equal) to the
`begin()` of the `{100}` vector.

The implementation currently includes a **subset** of the features found `std::vector`
and is described below. 

The multivector is a totally ordered container class for hierarchies.
It supports the following vector operations:

[source,c++]
----
item_reference operator[](int index) 
const_item_reference operator[](int index) const 

void clear() 
void pop_back() 

bool empty() const 

size_t size() const 
cursor begin() 
const_cursor begin() const 
const_cursor cbegin() const 

cursor end() 
const_cursor end() const 
const_cursor cend() const 
----

There is an additional constructor that takes a cursor:

[source,c++]
----
multivector(cursor c)
----

`c` will become the root of a new multivector, its contents will be copied.

=== Download and Integration

The multivector implementation is contained entirely in `multivector.h`.
and can be found at <https://github.com/wythe/multivector>.
There are no dependencies other than the STL.

Building is only required to run the tests and examples.

== Cursors

Cursors share both the properties of `std::vector` and a std::vector's iterator.
This in effect makes a cursor behave like a multivector.
There are three kinds of cursors, described in the following sections.

=== cursor

In addition to normal random-access iterator operations, cursors provide the
following functions:

Here are vector operations that are currently supported for cursors:

[source,c++]
----
    cursor begin() 
    cursor begin() const 
    cursor cbegin() const 
    cursor end() 
    cursor end() const 
    cursor cend() const 
    
    bool empty() const 
    size_t size() const 

    void reserve(size_t n)

    void clear()
    void pop_back()

    // emplace a value at the end and return a cursor to it.
    template <class... Args>
    cursor emplace(Args&&... args) 

    // emplace a value at the end.
    template <class... Args>
    void emplace_back(Args&&... args) 
----

Additional cursor navigation operations are available:

[source,c++]
----
// return a child cursor 
bool is_first_child() const // return true if this is the first child 
cursor parent() const // return a cursor to parent
bool is_root() const // true if this is the root cursor
----

Cursor validity is similar to that of vectors.
If a vector gets resized, then all its cursors are invalidated.
But any parent cursor is still valid.

=== ascending_cursor

An ascending cursor is a forward cursor.
`operator++` just goes up and to the left until the root.

For example:

[source,c++]
----
auto m = wythe::multivector<int>{1, {10, { 100, 101, 102}}, 2, 3, 4};
auto n = m.begin().begin().end();  // n points to one past 102
--n;                               // n points to 102
auto last = wythe::multivector<int>::ascending_cursor(n); // convert to an ascending cursor

while (!last.is_root()) {
    std::cout << *last << '\n';
    ++last;
}
----

will print out

----
102
101
100
10
1
----

The above code segment could be written more concisely using the
`to_ascending()` function:

[source,c++]
----
auto last = wythe::to_ascending(--m.begin().begin().end());
----

`ascending_cursor` supports the following vector operations:

[source,c++]
----
// vector operations
bool empty() const
size_t size() const
cursor begin()
cursor begin() const
cursor cbegin() const
----

Additional ascending cursor operations:

[source,c++]
----
bool is_root() const
----

=== linear_cursor

A linear cursor is also a forward iterator.
It traverses a multivector in a depth-first order.

The following code:

[source,c++]
----
auto m = wythe::multivector<int>{1, { 2, { 3 }, 4}};
for (auto i = wythe::to_linear(m.begin()); i!=m.end(); ++i)
	std::cout << *i << '\n';
----


will output:

----
1
2
3
4
----

Notice the automatic conversion from one type of cursor to another.

There are no operations for the linear cursor other than those of an input iterator.

== Functions

The multivector functions act upon one or more template cursor parameters that must
satisfy the cursor definition above.

=== get_root

[source,c++]
----
template <typename Cursor>
Cursor get_root(Cursor start)
----

Return the root cursor of a multivector given a cursor.
This is a log2(n) operation.

=== previous

[source,c++]
----
template <typename Cursor>
Cursor previous(Cursor self)
----

Return the previous cursor, either a sibling or parent.

=== recurse

[source,c++]
----
template <typename Cursor, typename Action>
void recurse(Cursor parent, Action action) 
----

Recursively descend and perform an action on each item.
The action must have a signature of:

`void action(Cursor current, Cursor parent)`

`current` is the current item visited, and `parent` is its parent.

The following example will print out all the items in a multivector:

[source,c++]
----
typedef wythe::multivector<int>::cursor int_cursor;
auto m = wythe::multivector<int>{1, { 2, { 3 }}};
wythe::recurse(m.root(), [](int_cursor c, int_cursor) { std::cout << *c << '\n'; }
----

=== recurse (2)

[source,c++]
----
template <typename Cursor, typename Action>
void recurse(Cursor parent, Action action_down, Action action_up, int level = 0) 
----

This version of recurse is similar to the above, except it also performs and action on
the way up.
Also, the current depth in the tree will be provided.
The `to_text` function is written using this.

=== compact_string

[source,c++]
----
inline std::string compact_string(Cursor parent);
inline std::string compact_string(const multivector<T> & tree);
----

Conveniently return a compact string representation of a multivector.
It uses the above recurse method.

[source,c++]
----
auto m = wythe::multivector<int>{1, { 2, { 3 }}};
std::cout << wythe::compact_string(m.root());
----

prints:

`{1 {2 {3}}}`

=== to_text

[source,c++]
----
inline std::string to_text(Cursor parent)
inline std::string to_text(const multivector<T> & tree) 
----

Convert to a table string.
An example is provided in the introduction.

=== leaf

`inline Cursor leaf(Cursor c)`

Returns the last child of c or c if it is empty().

=== promote_last

`inline void promote_last(Cursor parent)`

Replace the last child with the children of the last child.
This should be rewritten to not be so specific.
Perhaps a `detach()` ability that removes a subtree as a multivector.

=== to_ascending

`inline typename Cursor::ascending_cursor_type to_ascending(Cursor parent)`

Convert a cursor to an ascending cursor.

=== to_linear

`inline typename Cursor::linear_type to_linear(Cursor parent)`

Convert a cursor to a linear cursor.

=== append

[source,c++]
----
template <typename Cursor, typename ConstCursor>
void append(Cursor parent, ConstCursor first, ConstCursor last) 

template <typename Cursor, typename ConstCursor>
void append(Cursor parent, ConstCursor from_parent)
----

Append (i.e., copy) the children of one cursor to the children of another.
The the children will be appended to any existing children.

== References

Below are other tree implementations and papers I looked at while developing multivector.
In general, they provide more capability than the multivector, but are node based.

* multivector has some commonalty with the boost property tree:
  [boost property tree](http://www.boost.org/doc/libs/1_59_0/doc/html/property_tree.html)

* [Adobe forest](http://stlab.adobe.com/classadobe_1_1forest.html)

* [tree.hh](http://tree.phi-sci.com/documentation.html)

* [Hierarchical Data Structures and Related Concepts for the C++ Standard Library](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3700.html)

